{
 "title": "New dashboard",
 "description": "SNMP-Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "In Octets Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInOctets{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Unicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Discard Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifInDiscards{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifInDiscards{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IN Error Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifInErrors{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifInErrors{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IN Multicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}